ors:
  engine:
    init_threads: 4
    preparation_mode: true
    source_file: ./files/mazowieckie-latest.osm.pbf
    graphs_root_path: ./graphs_build
    profiles:
      walking:
        enabled: true
        profile: foot-walking
        elevation: true
        encoder_options:
          block_fords: false
      bike-regular:
        enabled: true
        profile: cycling-regular
        encoder_options:
          consider_elevation: true
          turn_costs: true
          block_fords: false
        elevation: true

logging:
  level:
    root: WARN
    org.heigit: INFO
  file:
    name: ./logs/ors.log

